version: "3.9"

services:
  app:
    image: "ghcr.io/ccmbioinfo/stager:${ST_VERSION}"
    user: www-data
    environment:
      ST_SECRET_KEY:
      ST_DATABASE_URI: "mysql+pymysql://${MYSQL_CONNECTION_STRING}"
      MINIO_ENDPOINT:
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
      MINIO_REGION_NAME: hpc4health
      MSTEAMS_WEBHOOK_URL:
      SENDGRID_API_KEY:
      SENDGRID_EMAIL_TEMPLATE_ID:
      SENDGRID_TO_EMAIL:
      SENDGRID_FROM_EMAIL:
    ports:
      - "5000:5000"
    command: --preload --workers ${GUNICORN_WORKERS:-1}
    healthcheck:
      test: ["CMD", "./healthcheck.py"]
    restart: unless-stopped
    logging:
      driver: journald
