version: "3.9"

services:
  app:
    image: "ghcr.io/ccmbioinfo/stager:${ST_VERSION}"
    user: www-data
    environment:
      ST_SECRET_KEY:
      ST_DATABASE_URI: "mysql+pymysql://${MYSQL_CONNECTION_STRING}"
      SQLALCHEMY_SIDECAR: /var/tmp/sqlalchemy.fifo
      MINIO_ENDPOINT:
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
      MINIO_REGION_NAME: hpc4health
      MSTEAMS_WEBHOOK_URL:
      SENDGRID_API_KEY:
      SENDGRID_EMAIL_TEMPLATE_ID:
      SENDGRID_TO_EMAIL:
      SENDGRID_FROM_EMAIL:
      SLURM_ENDPOINT:
      SLURM_USER:
      SLURM_JWT:
      CRG2_ENTRYPOINT: /home/slurm/crg2/dnaseq_slurm_api.sh
    ports:
      - "5000:5000"
      - "9121:8080"
    command: --preload --workers ${GUNICORN_WORKERS:-1}
    tmpfs:
      - /tmp
    volumes:
      - log-fifo:/var/tmp
    healthcheck:
      test: ["CMD", "./healthcheck.py"]
    restart: unless-stopped
    logging:
      driver: journald
  sidecar-sqlalchemy:
    image: busybox
    init: true
    user: www-data
    command: tail -f -n +1 /var/log/stager/sqlalchemy.fifo
    volumes:
      - log-fifo:/var/log/stager:ro
    depends_on:
      - app
    restart: unless-stopped
    logging:
      driver: journald
volumes:
  log-fifo:
