version: "3.9"

x-common: &common
  restart: unless-stopped
  logging:
    driver: journald

x-app: &app
  image: "ghcr.io/ccmbioinfo/stager:${ST_VERSION}"
  user: www-data
  command: --preload --workers ${GUNICORN_WORKERS:-1}
  healthcheck:
    test: ["CMD", "./healthcheck.py"]
  <<: *common

x-env: &env
  MINIO_REGION_NAME: hpc4health
  MINIO_TLS: "true"
  MSTEAMS_WEBHOOK_URL:

services:
  app-hiraki:
    <<: *app
    environment:
      <<: *env
      ST_SECRET_KEY: "${HIRAKI_ST_SECRET_KEY}"
      ST_DATABASE_URI: "mysql+pymysql://${HIRAKI_MYSQL_CONNECTION_STRING}"
      MINIO_ENDPOINT: "${HIRAKI_MINIO_ENDPOINT}"
      MINIO_ACCESS_KEY: "${HIRAKI_MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${HIRAKI_MINIO_SECRET_KEY}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`stager-hiraki.ccm.sickkids.ca`) # && PathPrefix(`/api`)
      - traefik.http.routers.app.entrypoints=https
      # Assume this works for now, need to confirm with domains
      - traefik.http.middlewares.app.headers.accessControlAllowOriginList=https://stager.ccm.sickkids.ca
      - traefik.http.middlewares.app.headers.accessControlAllowMethods=GET,HEAD,POST,PUT,DELETE,OPTIONS,PATCH
      - traefik.http.middlewares.app.headers.accessControlAllowHeaders=Accept,Content-Type
      - traefik.http.middlewares.app.headers.accessControlAllowCredentials=true
      - traefik.http.middlewares.app.headers.frameDeny=true
  # app-hawkins:
  #   <<: *app
  #   environment:
  #     <<: *env
  #     ST_SECRET_KEY: "${HAWKINS_ST_SECRET_KEY}"
  #     ST_DATABASE_URI: "mysql+pymysql://${HAWKINS_MYSQL_CONNECTION_STRING}"
  #     MINIO_ENDPOINT: "${HAWKINS_MINIO_ENDPOINT}"
  #     MINIO_ACCESS_KEY: "${HAWKINS_MINIO_ACCESS_KEY}"
  #     MINIO_SECRET_KEY: "${HAWKINS_MINIO_SECRET_KEY}"
  proxy:
    image: traefik:2.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${PROJECT_ROOT:-.}/traefik:/etc/traefik"
    command:
      - --api.insecure
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=false
      - --accesslog
      - --log
      - --metrics.prometheus
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.https.http.tls
      - --entrypoints.https.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik and Prometheus endpoint
    <<: *common
