tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
      # Drop all weak cipher suites as reported by SSL Labs and NMap
      # This means that old browsers (IE11 pre-Windows 10, Safari 8 and older) will fail the handshake
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/bundle.crt
        keyFile: /etc/traefik/certs/star_ccm_sickkids_ca.key
http:
  routers:
    redirect:
      entryPoints:
        - https
      middlewares:
        - redirect
      rule: HostRegexp(`{host:.+}`)
      service: noop@internal
      tls: false
  middlewares:
    redirect:
      redirectScheme:
        scheme: https
        permanent: true
