tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/bundle.crt
        keyFile: /etc/traefik/certs/star_ccm_sickkids_ca.key
http:
  routers:
    redirect:
      entryPoints:
        - https
      middlewares:
        - redirect
      rule: HostRegexp(`{host:.+}`)
      service: noop@internal
      tls: false
  middlewares:
    redirect:
      redirectScheme:
        scheme: https
        permanent: true
