from typing_extensions import Required
from marshmallow_sqlalchemy import SQLAlchemyAutoSchema
from marshmallow import fields, ValidationError
from marshmallow.validate import And, Length, Range, Regexp
from .models import *


# These fields are model attributes but are not generated by the schemas. These fields should not be included in the input validation because they are a collection of items created by relationship(). Before input validation, filter out these fields.
exclude_user = [
    "groups",
    "password",
]  # Validation for password is handled separatedly since it's not a field in the model.
exclude_group = ["users"]
exclude_family = ["participants", "created_by", "updated_by"]
exclude_participant = [
    "family",
    "institution",
    "tissue_samples",
    "created_by",
    "updated_by",
]
exclude_tissue_sample = ["participant", "datasets", "created_by", "updated_by"]
exclude_dataset = [
    "tissue_sample",
    "linked_files",
    "discriminator",
    "analyses",
    "groups",
    "created_by",
    "updated_by",
]
exclude_analysis = ["pipeline", "assignee", "requester", "variants", "updated_by"]


class FamilySchema(SQLAlchemyAutoSchema):
    """
    POST /api/families
    """

    class Meta:
        model = Family
        include_fk = True
        load_instance = False
        exclude = ("created_by_id", "updated_by_id")


class ParticipantSchema(SQLAlchemyAutoSchema):
    """
    POST /api/participants
    """

    class Meta:
        model = Participant
        include_fk = True
        load_instance = False
        exclude = ("created_by_id", "updated_by_id")


class TissueSampleSchema(SQLAlchemyAutoSchema):
    """
    POST /api/tissue_samples
    """

    class Meta:
        model = TissueSample
        include_fk = True
        load_instance = False
        exclude = ("created_by_id", "updated_by_id")


class RNASeqDatasetSchema(SQLAlchemyAutoSchema):
    """
    POST /api/datasets
    - created_by_id and updated_by_id is not given as part of the request body and should therefore be excluded from validation
    - discriminator field is populated automatically when a new dataset is inserted into the database.
    - valid tissue_sample_id is required for the dataset to be linked
    """

    class Meta:
        model = RNASeqDataset
        # needs to be True so fks eg. dataset_type are properly validated
        include_fk = True
        load_instance = False
        exclude = ("created_by_id", "updated_by_id", "discriminator", "dataset_id")

    tissue_sample_id = fields.Integer(
        strict=True, required=True, validate=[Range(min=1)]
    )


class AnalysisSchema(SQLAlchemyAutoSchema):
    """
    POST /api/analyses
    - datasets is a list of integers to be linked with this given analysis
    """

    class Meta:
        model = Analysis
        include_fk = True
        load_instance = False
        exclude = (
            "assignee_id",
            "requester_id",
            "updated",
            "analysis_state",
            "requested",
            "updated_by_id",
        )

    datasets = fields.List(fields.Integer(), required=True, validate=Length(min=1))


class GroupSchema(SQLAlchemyAutoSchema):
    """
    POST /api/groups
    """

    class Meta:
        model = Group
        include_fk = True
        load_instance = False

    group_code = fields.String(
        required=True,
        validate=And(
            Regexp(regex="^[a-z,0-9,-]*$"),
            Regexp(
                regex="^(?!results-$).*$",
                error="A group codename cannot start with 'results-'",
                # madmin.py::stager_buckets_policy
            ),
            Length(min=3),
            Length(max=50),
        ),
    )

    group_name = fields.String(
        required=True, validate=And(Length(min=1), Length(max=250))
    )


class UserSchema(SQLAlchemyAutoSchema):
    """
    POST /api/users
    - password_hash is generated and should not be included in the user input.
    """

    class Meta:
        model = User
        include_fk = True
        load_instance = False
        exclude = ["password_hash"]

    def verify_email(email: str):
        space = email.find(" ")
        at = email.find("@")
        dot = email.find(".", at)
        if not (space == -1 and at > 0 and dot > at + 1):
            raise ValidationError("Invalid email")

    username = fields.String(required=True, validate=And(Length(min=1), Length(max=30)))
    email = fields.String(
        required=True, validate=And(verify_email, Length(min=1), Length(max=150))
    )
