"""updates to participant table

Revision ID: 00462e44baf0
Revises: 0e8799c17f5a
Create Date: 2020-10-26 20:04:08.923131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "00462e44baf0"
down_revision = "0e8799c17f5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "participant",
        "participant_type",
        existing_type=mysql.ENUM("Proband", "Mother", "Father", "Sibling"),
        nullable=True,
    )
    op.alter_column(
        "participant",
        "sex",
        existing_type=mysql.ENUM("Male", "Female", "Other"),
        nullable=True,
    )
    op.execute(
        "ALTER TABLE participant CHANGE COLUMN participant_type participant_type ENUM('Proband', 'Parent', 'Sibling');"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "participant",
        "sex",
        existing_type=mysql.ENUM("Male", "Female", "Other"),
        nullable=False,
    )
    op.alter_column(
        "participant",
        "participant_type",
        existing_type=mysql.ENUM("Proband", "Mother", "Father", "Sibling"),
        nullable=False,
    )
    op.execute(
        "ALTER TABLE participant CHANGE COLUMN participant_type participant_type ENUM('Proband', 'Mother', 'Father, 'Sibling');"
    )
    # ### end Alembic commands ###
