"""gene viewer schema

Revision ID: 0d636c534481
Revises: 2a2bc309568d
Create Date: 2021-04-05 18:02:53.459994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d636c534481"
down_revision = "2a2bc309568d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gene",
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column("hgnc_gene_id", sa.Integer(), nullable=True),
        sa.Column("ensembl_id", sa.Integer(), nullable=True),
        sa.Column("gene", sa.String(length=50), nullable=True),
        sa.Column("hgnc_gene_name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("gene_id"),
        sa.UniqueConstraint("ensembl_id"),
        sa.UniqueConstraint("hgnc_gene_id"),
    )
    op.create_table(
        "variant",
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=False),
        sa.Column("reference_allele", sa.String(length=150), nullable=False),
        sa.Column("alt_allele", sa.String(length=150), nullable=False),
        sa.Column("variation", sa.String(length=50), nullable=False),
        sa.Column("refseq_change", sa.String(length=250), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=True),
        sa.Column("conserved_in_20_mammals", sa.Float(), nullable=True),
        sa.Column("sift_score", sa.Float(), nullable=True),
        sa.Column("polyphen_score", sa.Float(), nullable=True),
        sa.Column("cadd_score", sa.Float(), nullable=True),
        sa.Column("gnomad_af", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis.analysis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"], ["gene.gene_id"], onupdate="cascade", ondelete="restrict"
        ),
        sa.PrimaryKeyConstraint("variant_id"),
    )
    op.create_table(
        "genotype",
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("zygosity", sa.String(length=50), nullable=True),
        sa.Column("burden", sa.Integer(), nullable=True),
        sa.Column("alt_depths", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis.analysis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.dataset_id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variant.variant_id"],
        ),
        sa.PrimaryKeyConstraint("variant_id", "analysis_id", "dataset_id"),
    )
    op.create_unique_constraint(
        "datasets_analyses_composite_fk",
        "datasets_analyses",
        ["dataset_id", "analysis_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("datasets_analyses_composite_fk", "datasets_analyses")
    op.drop_table("genotype")
    op.drop_table("variant")
    op.drop_table("gene")
    # ### end Alembic commands ###
