"""RNASeq updates

Revision ID: 0d8af5e5d7f4
Revises: 1391a456d774
Create Date: 2020-09-18 13:50:42.855710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8af5e5d7f4'
down_revision = '1391a456d774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rnaseq_dataset', sa.Column('library_strand', sa.Enum('Forward', 'Reverse', 'Unstranded', name='librarystrand'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rnaseq_dataset', 'library_strand')
    # ### end Alembic commands ###
