"""adding month of birth field with check

Revision ID: 0e8799c17f5a
Revises: f8862eed0498
Create Date: 2020-10-07 16:52:17.103358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0e8799c17f5a"
down_revision = "f8862eed0498"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participant", sa.Column("month_of_birth", sa.Date(), nullable=True))
    op.execute("ALTER TABLE participant ADD CHECK (DAY(month_of_birth) = 1);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant", "month_of_birth")
    # ### end Alembic commands ###
