"""Alter Analysis table to also reflect name_by schema and field changes

Revision ID: 3cdd5ef34153
Revises: 4a075eaadd1a
Create Date: 2020-12-03 16:12:58.404162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3cdd5ef34153"
down_revision = "4a075eaadd1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis", sa.Column("assigned_by_id", sa.Integer(), nullable=True))
    op.add_column(
        "analysis", sa.Column("requested_by_id", sa.Integer(), nullable=False)
    )
    op.add_column("analysis", sa.Column("updated_by_id", sa.Integer(), nullable=False))
    op.drop_constraint("analysis_ibfk_1", "analysis", type_="foreignkey")
    op.drop_constraint("analysis_ibfk_4", "analysis", type_="foreignkey")
    op.drop_constraint("analysis_ibfk_3", "analysis", type_="foreignkey")
    op.create_foreign_key(
        None, "analysis", "user", ["requested_by_id"], ["user_id"], onupdate="cascade"
    )
    op.create_foreign_key(
        None, "analysis", "user", ["updated_by_id"], ["user_id"], onupdate="cascade"
    )
    op.create_foreign_key(
        None, "analysis", "user", ["assigned_by_id"], ["user_id"], onupdate="cascade"
    )
    op.drop_column("analysis", "assignee")
    op.drop_column("analysis", "updated_by")
    op.drop_column("analysis", "requester")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis",
        sa.Column("requester", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "analysis",
        sa.Column("updated_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "analysis",
        sa.Column("assignee", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "analysis", type_="foreignkey")
    op.drop_constraint(None, "analysis", type_="foreignkey")
    op.drop_constraint(None, "analysis", type_="foreignkey")
    op.create_foreign_key(
        "analysis_ibfk_3",
        "analysis",
        "user",
        ["requester"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.create_foreign_key(
        "analysis_ibfk_4",
        "analysis",
        "user",
        ["updated_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.create_foreign_key(
        "analysis_ibfk_1",
        "analysis",
        "user",
        ["assignee"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.drop_column("analysis", "updated_by_id")
    op.drop_column("analysis", "requested_by_id")
    op.drop_column("analysis", "assigned_by_id")
    # ### end Alembic commands ###
