"""Alter Analysis table field names for consistency

Revision ID: 403cfa4b6184
Revises: 4a075eaadd1a
Create Date: 2020-12-03 20:09:53.021481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '403cfa4b6184'
down_revision = '4a075eaadd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('analysis', sa.Column('requester_id', sa.Integer(), nullable=False))
    op.drop_constraint('analysis_ibfk_3', 'analysis', type_='foreignkey')
    op.drop_constraint('analysis_ibfk_1', 'analysis', type_='foreignkey')
    op.create_foreign_key(None, 'analysis', 'user', ['requester_id'], ['user_id'], onupdate='cascade')
    op.create_foreign_key(None, 'analysis', 'user', ['assignee_id'], ['user_id'], onupdate='cascade')
    op.drop_column('analysis', 'requester')
    op.drop_column('analysis', 'assignee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('assignee', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('analysis', sa.Column('requester', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.create_foreign_key('analysis_ibfk_1', 'analysis', 'user', ['assignee'], ['user_id'], onupdate='CASCADE')
    op.create_foreign_key('analysis_ibfk_3', 'analysis', 'user', ['requester'], ['user_id'], onupdate='CASCADE')
    op.drop_column('analysis', 'requester_id')
    op.drop_column('analysis', 'assignee_id')
    # ### end Alembic commands ###
