"""adding metadata type tracking

Revision ID: 472c86a67692
Revises: 7dd40bd16801
Create Date: 2020-10-26 22:03:57.540552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '472c86a67692'
down_revision = '7dd40bd16801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadataset_type_dataset_type',
    sa.Column('metadataset_type_dataset_type_id', sa.Integer(), nullable=False),
    sa.Column('meta_dataset_type', sa.Enum('Exome', 'Genome', 'RNA', 'Other', name='metadatasettype'), nullable=False),
    sa.Column('dataset_type', sa.Enum('RES', 'CES', 'WES', 'CPS', 'RCS', 'RDC', 'RDE', 'RGS', 'CGS', 'WGS', 'RRS', 'RLM', 'RMM', 'RTA', name='datasettype'), nullable=False),
    sa.PrimaryKeyConstraint('metadataset_type_dataset_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadataset_type_dataset_type')
    # ### end Alembic commands ###
