"""Add user relationships and rename fields

Revision ID: 4a075eaadd1a
Revises: 8de51438e585
Create Date: 2020-12-03 15:34:18.217683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4a075eaadd1a"
down_revision = "8de51438e585"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("created_by_id", sa.Integer(), nullable=False))
    op.add_column("dataset", sa.Column("updated_by_id", sa.Integer(), nullable=False))
    op.drop_constraint("dataset_ibfk_1", "dataset", type_="foreignkey")
    op.drop_constraint("dataset_ibfk_3", "dataset", type_="foreignkey")
    op.create_foreign_key(
        None, "dataset", "user", ["created_by_id"], ["user_id"], onupdate="cascade"
    )
    op.create_foreign_key(
        None, "dataset", "user", ["updated_by_id"], ["user_id"], onupdate="cascade"
    )
    op.drop_column("dataset", "created_by")
    op.drop_column("dataset", "updated_by")
    op.add_column("family", sa.Column("created_by_id", sa.Integer(), nullable=False))
    op.add_column("family", sa.Column("updated_by_id", sa.Integer(), nullable=False))
    op.drop_constraint("family_ibfk_1", "family", type_="foreignkey")
    op.drop_constraint("family_ibfk_2", "family", type_="foreignkey")
    op.create_foreign_key(
        None, "family", "user", ["updated_by_id"], ["user_id"], onupdate="cascade"
    )
    op.create_foreign_key(
        None, "family", "user", ["created_by_id"], ["user_id"], onupdate="cascade"
    )
    op.drop_column("family", "created_by")
    op.drop_column("family", "updated_by")
    op.add_column(
        "participant", sa.Column("created_by_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "participant", sa.Column("updated_by_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("participant_ibfk_1", "participant", type_="foreignkey")
    op.drop_constraint("participant_ibfk_3", "participant", type_="foreignkey")
    op.create_foreign_key(
        None, "participant", "user", ["created_by_id"], ["user_id"], onupdate="cascade"
    )
    op.create_foreign_key(
        None, "participant", "user", ["updated_by_id"], ["user_id"], onupdate="cascade"
    )
    op.drop_column("participant", "updated_by")
    op.drop_column("participant", "created_by")
    op.add_column(
        "tissue_sample", sa.Column("created_by_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "tissue_sample", sa.Column("updated_by_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("tissue_sample_ibfk_1", "tissue_sample", type_="foreignkey")
    op.drop_constraint("tissue_sample_ibfk_3", "tissue_sample", type_="foreignkey")
    op.create_foreign_key(
        None,
        "tissue_sample",
        "user",
        ["updated_by_id"],
        ["user_id"],
        onupdate="cascade",
    )
    op.create_foreign_key(
        None,
        "tissue_sample",
        "user",
        ["created_by_id"],
        ["user_id"],
        onupdate="cascade",
    )
    op.drop_column("tissue_sample", "created_by")
    op.drop_column("tissue_sample", "updated_by")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tissue_sample",
        sa.Column("updated_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tissue_sample",
        sa.Column("created_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "tissue_sample", type_="foreignkey")
    op.drop_constraint(None, "tissue_sample", type_="foreignkey")
    op.create_foreign_key(
        "tissue_sample_ibfk_3",
        "tissue_sample",
        "user",
        ["updated_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.create_foreign_key(
        "tissue_sample_ibfk_1",
        "tissue_sample",
        "user",
        ["created_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.drop_column("tissue_sample", "updated_by_id")
    op.drop_column("tissue_sample", "created_by_id")
    op.add_column(
        "participant",
        sa.Column("created_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "participant",
        sa.Column("updated_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "participant", type_="foreignkey")
    op.drop_constraint(None, "participant", type_="foreignkey")
    op.create_foreign_key(
        "participant_ibfk_3",
        "participant",
        "user",
        ["updated_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.create_foreign_key(
        "participant_ibfk_1",
        "participant",
        "user",
        ["created_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.drop_column("participant", "updated_by_id")
    op.drop_column("participant", "created_by_id")
    op.add_column(
        "family",
        sa.Column("updated_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "family",
        sa.Column("created_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "family", type_="foreignkey")
    op.drop_constraint(None, "family", type_="foreignkey")
    op.create_foreign_key(
        "family_ibfk_2",
        "family",
        "user",
        ["updated_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.create_foreign_key(
        "family_ibfk_1",
        "family",
        "user",
        ["created_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.drop_column("family", "updated_by_id")
    op.drop_column("family", "created_by_id")
    op.add_column(
        "dataset",
        sa.Column("updated_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "dataset",
        sa.Column("created_by", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "dataset", type_="foreignkey")
    op.drop_constraint(None, "dataset", type_="foreignkey")
    op.create_foreign_key(
        "dataset_ibfk_3",
        "dataset",
        "user",
        ["updated_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.create_foreign_key(
        "dataset_ibfk_1",
        "dataset",
        "user",
        ["created_by"],
        ["user_id"],
        onupdate="CASCADE",
    )
    op.drop_column("dataset", "updated_by_id")
    op.drop_column("dataset", "created_by_id")
    # ### end Alembic commands ###
