"""gene pull schema changes

Revision ID: 51c0fa946d16
Revises: 2fac0d8a5b76
Create Date: 2021-03-24 17:34:28.596604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "51c0fa946d16"
down_revision = "2fac0d8a5b76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analyzed_variant")
    op.add_column(
        "datasets_analyses", sa.Column("alt_depths", sa.Integer(), nullable=True)
    )
    op.add_column("datasets_analyses", sa.Column("burden", sa.Integer(), nullable=True))
    op.add_column(
        "datasets_analyses", sa.Column("zygosity", sa.String(length=50), nullable=True)
    )
    op.add_column("variant", sa.Column("analysis_id", sa.Integer(), nullable=False))
    op.alter_column(
        "variant",
        "alt_allele",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    op.alter_column(
        "variant",
        "reference_allele",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "variant", "analysis", ["analysis_id"], ["analysis_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "variant", type_="foreignkey")
    op.alter_column(
        "variant",
        "reference_allele",
        existing_type=sa.String(length=150),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "variant",
        "alt_allele",
        existing_type=sa.String(length=150),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("variant", "analysis_id")
    op.drop_column("datasets_analyses", "zygosity")
    op.drop_column("datasets_analyses", "burden")
    op.drop_column("datasets_analyses", "alt_depths")
    op.create_table(
        "analyzed_variant",
        sa.Column("variant_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("analysis_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("zygosity", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("burden", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("alt_depths", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["analysis.analysis_id"], name="analyzed_variant_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["variant.variant_id"], name="analyzed_variant_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("variant_id", "analysis_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
