"""Support aliases and use ENSGs as primary key

Revision ID: 5c31345e42ec
Revises: ea0af75da395
Create Date: 2021-05-05 19:35:06.190272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c31345e42ec"
down_revision = "ea0af75da395"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gene",
        sa.Column("ensembl_id", sa.Integer(), nullable=False),
        sa.Column("hgnc_id", sa.Integer(), nullable=True),
        sa.Column("ncbi_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ensembl_id"),
        sa.UniqueConstraint("hgnc_id"),
        sa.UniqueConstraint("ncbi_id"),
    )
    op.create_table(
        "gene_alias",
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("ensembl_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["ensembl_id"], ["gene.ensembl_id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.UniqueConstraint("ensembl_id", "name"),
    )
    op.add_column("variant", sa.Column("ensembl_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "variant",
        "gene",
        ["ensembl_id"],
        ["ensembl_id"],
        onupdate="cascade",
        ondelete="restrict",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "variant", type_="foreignkey")
    op.drop_column("variant", "ensembl_id")
    op.drop_table("gene_alias")
    op.drop_table("gene")
    # ### end Alembic commands ###
