"""support for positional-based querying

Revision ID: 5e69ca582792
Revises: 42a60aeca550
Create Date: 2021-05-13 16:02:51.702749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5e69ca582792"
down_revision = "42a60aeca550"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("variant_ibfk_2", "variant", type_="foreignkey")
    op.drop_column("variant", "gene_id")
    op.drop_index("ensembl_id", table_name="gene")
    op.drop_index("hgnc_gene_id", table_name="gene")
    op.drop_table("gene")

    op.create_table(
        "gene",
        sa.Column("ensembl_id", sa.Integer(), nullable=False),
        sa.Column("hgnc_id", sa.Integer(), nullable=True),
        sa.Column("ncbi_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ensembl_id"),
        sa.UniqueConstraint("hgnc_id"),
        sa.UniqueConstraint("ncbi_id"),
    )

    op.create_table(
        "gene_alias",
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("ensembl_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["ensembl_id"], ["gene.ensembl_id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.UniqueConstraint("ensembl_id", "name"),
    )

    op.add_column(
        "variant", sa.Column("chromosome", sa.String(length=2), nullable=False)
    )
    op.alter_column(
        "variant",
        "alt_allele",
        existing_type=mysql.VARCHAR(length=150),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "variant",
        "position",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "variant",
        "reference_allele",
        existing_type=mysql.VARCHAR(length=150),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "variant",
        "refseq_change",
        existing_type=mysql.VARCHAR(length=250),
        type_=sa.String(length=500),
        existing_nullable=True,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gene_alias")
    op.drop_table("gene")

    op.create_table(
        "gene",
        sa.Column("gene_id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("hgnc_gene_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ensembl_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("gene", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("hgnc_gene_name", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("gene_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("hgnc_gene_id", "gene", ["hgnc_gene_id"], unique=True)
    op.create_index("ensembl_id", "gene", ["ensembl_id"], unique=True)

    op.add_column(
        "variant",
        sa.Column("gene_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "variant_ibfk_2",
        "variant",
        "gene",
        ["gene_id"],
        ["gene_id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )

    op.alter_column(
        "variant",
        "refseq_change",
        existing_type=sa.String(length=500),
        type_=mysql.VARCHAR(length=250),
        existing_nullable=True,
    )
    op.alter_column(
        "variant",
        "reference_allele",
        existing_type=sa.String(length=300),
        type_=mysql.VARCHAR(length=150),
        existing_nullable=False,
    )
    op.alter_column(
        "variant",
        "position",
        existing_type=sa.Integer(),
        type_=mysql.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "variant",
        "alt_allele",
        existing_type=sa.String(length=300),
        type_=mysql.VARCHAR(length=150),
        existing_nullable=False,
    )
    op.drop_column("variant", "chromosome")

    # ### end Alembic commands ###
