"""test_value

Revision ID: 629de526d4dc
Revises: 83abd5d883b6
Create Date: 2021-12-08 19:05:59.897524

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql
from sqlalchemy import String, orm, Table, Column, Integer, ForeignKey
from sqlalchemy.sql import select, table, column
from app.models import *

# revision identifiers, used by Alembic.
revision = '629de526d4dc'
down_revision = '83abd5d883b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('analysis_id_2', table_name='genotype')
    dataset = table(
        "dataset",
        column("dataset_id", Integer),
        column("discriminator", mysql.ENUM("dataset", "rnaseq_dataset")),
        column("dataset_type", String),
    )

    op.execute(
        dataset.update()
        .where(dataset.c.dataset_type != op.inline_literal("RRS"))
        .values({"discriminator": op.inline_literal("dataset")})
    )

    op.execute(
        dataset.update()
        .where(dataset.c.dataset_type == op.inline_literal("RRS"))
    .values({"discriminator": op.inline_literal("rnaseq_dataset")})
    )

    op.alter_column(
        "dataset",
        "discriminator",
        existing_type=mysql.ENUM("dataset", "rnaseq_dataset"),
        nullable=False,
    )
    op.execute(
        "insert into rnaseq_dataset (dataset_id) select dataset_id from dataset where dataset_type = 'RRS'"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'discriminator',
           existing_type=mysql.ENUM('dataset', 'rnaseq_dataset'),
           nullable=True)
    dataset = table(
        "dataset",
        column("dataset_id", Integer),
        column("discriminator", mysql.ENUM("dataset", "rnaseq_dataset")),
        column("dataset_type", String),
    )
    op.execute(dataset.update().values({"discriminator":None}))
    op.execute("delete from rnaseq_dataset")
    #op.create_index('analysis_id_2', 'genotype', ['analysis_id', 'variant_id'], unique=False)
    # ### end Alembic commands ###
