"""empty message

Revision ID: 72f108f4cb59
Revises: 9876f0c4fd80
Create Date: 2020-08-04 20:47:49.679713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72f108f4cb59'
down_revision = '9876f0c4fd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('dataset', 'entered',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('dataset', 'entered_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('dataset', 'extraction_protocol',
               existing_type=mysql.ENUM('Something'),
               nullable=True)
    op.alter_column('dataset', 'input_hpf_path',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('dataset', 'sequencing_centre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'sequencing_centre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('dataset', 'input_hpf_path',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('dataset', 'extraction_protocol',
               existing_type=mysql.ENUM('Something'),
               nullable=False)
    op.alter_column('dataset', 'entered_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('dataset', 'entered',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('dataset', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
