"""empty message

Revision ID: 77b47135070f
Revises: a7e88bf7d581
Create Date: 2020-08-07 19:41:43.603973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b47135070f'
down_revision = 'a7e88bf7d581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('solved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'solved')
    # ### end Alembic commands ###
