"""non-nullable-discriminator

Revision ID: 7a933f756ef9
Revises: 83abd5d883b6
Create Date: 2021-12-08 21:29:02.550679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import String, Integer
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = "7a933f756ef9"
down_revision = "83abd5d883b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dataset = table(
        "dataset",
        column("dataset_id", Integer),
        column("discriminator", mysql.ENUM("dataset", "rnaseq_dataset")),
        column("dataset_type", String),
    )

    op.execute(
        dataset.update()
        .where(dataset.c.dataset_type != op.inline_literal("RRS"))
        .values({"discriminator": op.inline_literal("dataset")})
    )

    op.execute(
        dataset.update()
        .where(dataset.c.dataset_type == op.inline_literal("RRS"))
        .values({"discriminator": op.inline_literal("rnaseq_dataset")})
    )

    op.alter_column(
        "dataset",
        "discriminator",
        existing_type=mysql.ENUM("dataset", "rnaseq_dataset"),
        nullable=False,
    )
    op.execute(
        "insert into rnaseq_dataset (dataset_id) select dataset_id from dataset where dataset_type = 'RRS'"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset",
        "discriminator",
        existing_type=mysql.ENUM("dataset", "rnaseq_dataset"),
        nullable=True,
    )
    dataset = table(
        "dataset",
        column("dataset_id", Integer),
        column("discriminator", mysql.ENUM("dataset", "rnaseq_dataset")),
        column("dataset_type", String),
    )
    op.execute(dataset.update().values({"discriminator": None}))
    op.execute("delete from rnaseq_dataset")
    # ### end Alembic commands ###
