"""adding deactivated column to user table

Revision ID: 7dd40bd16801
Revises: 00462e44baf0
Create Date: 2020-10-26 20:48:20.243113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd40bd16801'
down_revision = '00462e44baf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deactivated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deactivated')
    # ### end Alembic commands ###
