"""Add MinIO credentials to User table

Revision ID: 8de51438e585
Revises: 567a9f6ac119
Create Date: 2020-12-02 19:26:15.268460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de51438e585'
down_revision = '567a9f6ac119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('minio_access_key', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('minio_secret_key', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'minio_secret_key')
    op.drop_column('user', 'minio_access_key')
    # ### end Alembic commands ###
