"""adding Other to ParticipantType, tracking Institution

Revision ID: 8ded098b251c
Revises: a8abbee2352a
Create Date: 2020-12-17 18:42:07.749240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ded098b251c'
down_revision = 'a8abbee2352a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('institution', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('institution')
    )
    op.add_column('participant', sa.Column('institution', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'participant', 'institution', ['institution'], ['institution'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'institution')
    op.drop_table('institution')
    # ### end Alembic commands ###
