"""empty message

Revision ID: a7e88bf7d581
Revises: 72f108f4cb59
Create Date: 2020-08-07 14:45:16.298681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7e88bf7d581'
down_revision = '72f108f4cb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dataset_ibfk_2', 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'entered_by')
    op.drop_column('dataset', 'entered')
    op.drop_column('tissue_sample', 'solved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tissue_sample', sa.Column('solved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('dataset', sa.Column('entered', mysql.DATETIME(), nullable=True))
    op.add_column('dataset', sa.Column('entered_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dataset_ibfk_2', 'dataset', 'user', ['entered_by'], ['user_id'], onupdate='CASCADE')
    # ### end Alembic commands ###
