"""Change extraction protocol to freetext and Institution to not nullable and unique

Revision ID: ded8d42ffcb7
Revises: 2a2bc309568d
Create Date: 2021-02-03 14:24:31.175157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ded8d42ffcb7"
down_revision = "2a2bc309568d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dataset", "extraction_protocol", existing_type=mysql.ENUM("Something")
    )
    op.alter_column(
        "institution",
        "institution",
        existing_type=mysql.VARCHAR(length=100),
        nullable=False,
    )
    op.create_unique_constraint(None, "institution", ["institution"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "institution", type_="unique")
    op.alter_column(
        "institution",
        "institution",
        existing_type=mysql.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "dataset",
        "extraction_protocol",
        existing_type=mysql.ENUM("Something"),
    )
    # ### end Alembic commands ###
