"""Support gene aliases and use ENSGs as primary key

Revision ID: ea0af75da395
Revises: 42a60aeca550
Create Date: 2021-05-05 19:30:14.711438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ea0af75da395"
down_revision = "42a60aeca550"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("variant_ibfk_2", "variant", type_="foreignkey")
    op.drop_column("variant", "gene_id")
    op.drop_index("ensembl_id", table_name="gene")
    op.drop_index("hgnc_gene_id", table_name="gene")
    op.drop_table("gene")

    op.create_table(
        "gene",
        sa.Column("ensembl_id", sa.Integer(), nullable=False),
        sa.Column("hgnc_id", sa.Integer(), nullable=True),
        sa.Column("ncbi_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ensembl_id"),
        sa.UniqueConstraint("hgnc_id"),
        sa.UniqueConstraint("ncbi_id"),
    )
    op.create_table(
        "gene_alias",
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("ensembl_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["ensembl_id"], ["gene.ensembl_id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.UniqueConstraint("ensembl_id", "name"),
    )
    op.add_column("variant", sa.Column("ensembl_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "variant",
        "gene",
        ["ensembl_id"],
        ["ensembl_id"],
        onupdate="cascade",
        ondelete="restrict",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "variant", type_="foreignkey")
    op.drop_column("variant", "ensembl_id")
    op.drop_table("gene_alias")
    op.drop_table("gene")

    op.create_table(
        "gene",
        sa.Column("gene_id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("hgnc_gene_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ensembl_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("gene", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("hgnc_gene_name", mysql.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("gene_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("hgnc_gene_id", "gene", ["hgnc_gene_id"], unique=True)
    op.create_index("ensembl_id", "gene", ["ensembl_id"], unique=True)
    op.add_column(
        "variant",
        sa.Column("gene_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "variant_ibfk_2",
        "variant",
        "gene",
        ["gene_id"],
        ["gene_id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
