"""empty message

Revision ID: f5d6895299c6
Revises: 1986c1c89718
Create Date: 2020-05-21 16:49:04.167723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d6895299c6'
down_revision = '1986c1c89718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('tissue_sample_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dataset', 'tissue_sample', ['tissue_sample_id'], ['tissue_sample_id'])
    op.add_column('participant', sa.Column('family_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'participant', 'family', ['family_id'], ['family_id'])
    op.add_column('tissue_sample', sa.Column('participant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tissue_sample', 'participant', ['participant_id'], ['participant_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tissue_sample', type_='foreignkey')
    op.drop_column('tissue_sample', 'participant_id')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'family_id')
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'tissue_sample_id')
    # ### end Alembic commands ###
